ChoferesBundle\Entity\Canon:
    type: entity
    table: canon
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        monto:
            type: decimal
            precision: 10
            scale: 2
            options:
                default: 0
        fechaDesde:
            type: datetime
            nullable: true
            column: fecha_desde
        fechaHasta:
            type: datetime
            nullable: true
            column: fecha_hasta
        vigente:
            type: boolean
            nullable: false
            options:
                default: true
            column: vigente
    lifecycleCallbacks: {  }
