ChoferesBundle\Entity\Chofer:
    type: entity
    table: chofer
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        apellido:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        dni:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
        triCode:
            type: string
            nullable: true
            length: 18
            options:
                fixed: false
        cuil:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        cuilEmpresa:
            type: string
            nullable: true
            length: 11
            options:
                fixed: false
            column: cuil_empresa
        tieneCursoBasico:
            type: boolean
            nullable: false
            options:
                default: false
            column: tiene_curso_basico
        matricula:
            type: string
            nullable: true
            length: 18
            options:
                fixed: false
        estaActivo:
            type: boolean
            nullable: false
            options:
                default: true
            column: esta_activo
        fechaBorrado:
            type: datetime
            nullable: true
            column: fecha_borrado
    oneToMany:
        choferCursos:
            targetEntity: ChoferCurso
            mappedBy: chofer
    manyToOne:
        usuarioQueBorro:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario_que_borro:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
