ChoferesBundle\Entity\Curso:
    type: entity
    table: curso
    indexes:
        prestador_curso_idx:
            columns:
                - prestador_id
        docente_curso_idx:
            columns:
                - docente_id
        tipoCurso_curso_idx:
            columns:
                - tipoCurso_id
        sede_curso_idx:
            columns:
                - sede_id
        estado_curso_idx:
            columns:
                - estado_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fechaInicio:
            type: datetime
            nullable: false
            column: fecha_inicio
        fechaFin:
            type: datetime
            nullable: false
            column: fecha_fin
        fechaCreacion:
            type: datetime
            nullable: false
            column: fecha_creacion
        codigo:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        comprobante:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        docente:
            targetEntity: Docente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                docente_id:
                    referencedColumnName: id
            orphanRemoval: false
        estado:
            targetEntity: EstadoCurso
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                estado_id:
                    referencedColumnName: id
            orphanRemoval: false
        prestador:
            targetEntity: Prestador
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                prestador_id:
                    referencedColumnName: id
            orphanRemoval: false
        sede:
            targetEntity: Sede
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sede_id:
                    referencedColumnName: id
            orphanRemoval: false
        tipocurso:
            targetEntity: TipoCurso
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipoCurso_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
