ChoferesBundle\Entity\Docente:
    type: entity
    table: docente
    indexes:
        prestador_docente_idx:
            columns:
                - prestador_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        apellido:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        dni:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    manyToOne:
        prestador:
            targetEntity: Prestador
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                prestador_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
