ChoferesBundle\Entity\EstadoAuditoria:
    type: entity
    table: estado_auditoria
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
    oneToMany:
        auditorias:
            targetEntity: Auditoria
            mappedBy: estado
