ChoferesBundle\Entity\Prestador:
    type: entity
    table: prestador
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        cuit:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        direccion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        telefono:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        mail:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        logo:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
