ChoferesBundle\Entity\TipoCurso:
    type: entity
    table: tipo_curso
    indexes:
        canon_idx:
            columns: [ canon_id ]
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    manyToOne:
        canon:
            targetEntity: Canon
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                canon_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
