choferes:
    resource: "@ChoferesBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:     /login
    defaults: { _controller: ChoferesBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

default_security_target:
    path:     /usuario

unauthorized:
    path:     /unauthorized
    defaults: { _controller: ChoferesBundle:Default:unauthorized }
