security:
    providers:
        in_memory:
            memory: ~

        db_provider:
            entity:
                class: ChoferesBundle:Usuario
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path:           /login
                check_path:           /login_check
                csrf_provider:        security.csrf.token_manager
                default_target_path:  default_security_target
            logout:
                path:   /logout
                target: /login
            remember_me:
                secret: '%secret%'
                lifetime: 31536000

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/descargar-certificados/(.+), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/generate-captcha/gcb_captcha, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/chofer, roles: [ROLE_ADMIN, ROLE_CNTSV, ROLE_PRESTADOR] }
        - { path: ^/chofercurso, roles: [ROLE_ADMIN] }
        - { path: ^/curso, roles: [ROLE_ADMIN, ROLE_PRESTADOR, ROLE_CNTSV] }
        - { path: ^/docente, roles: [ROLE_ADMIN, ROLE_PRESTADOR, ROLE_CNTSV] }
        - { path: ^/estadocurso, roles: [ROLE_ADMIN] }
        - { path: ^/prestador, roles: [ROLE_ADMIN, ROLE_CNTSV] }
        - { path: ^/rol, roles: [ROLE_ADMIN] }
        - { path: ^/sede, roles: [ROLE_ADMIN, ROLE_PRESTADOR, ROLE_CNTSV] }
        - { path: ^/tipocurso, roles: [ROLE_ADMIN] }
        - { path: ^/usuario, roles: [ROLE_ADMIN] }
        - { path: ^/usuarioprestador, roles: [ROLE_ADMIN] }
        - { path: ^/auditoria, roles: [ROLE_AUDITOR] }

        - { path: ^/redirect, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/en_construccion, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/cambiar_password, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/consulta, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/reporte, roles: [ROLE_ADMIN, ROLE_CNTSV, ROLE_CENT, ROLE_CNRT] }
        - { path: ^/(.+), roles: ROLE_ADMIN }

    encoders:
        ChoferesBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12

    access_denied_url: /unauthorized
