services:
    choferes.servicios.usuario:
        class: ChoferesBundle\Servicios\UsuarioService
        arguments:
            entityManager: @doctrine.orm.entity_manager
    choferes.servicios.chofer:
        class: ChoferesBundle\Servicios\ChoferService
        arguments:
            entityManager: @doctrine.orm.entity_manager
            kernelCacheDir: "%kernel.cache_dir%"
            hashids: @hashids
            router: @router
            usuarioService: @choferes.servicios.usuario
        scope: request
    choferes.servicios.bajaAdministrativa:
        class: ChoferesBundle\Servicios\BajaAdministrativaService
        arguments:
            entityManager: @doctrine.orm.entity_manager
    choferes.servicios.curso:
        class: ChoferesBundle\Servicios\CursoService
        arguments:
            entityManager: @doctrine.orm.entity_manager
            pagoService: @choferes.servicios.pago
    choferes.servicios.pago:
        class: ChoferesBundle\Servicios\PagoService
        arguments:
            entityManager: @doctrine.orm.entity_manager
    choferes.servicios.excel:
        class: ChoferesBundle\Servicios\ExcelService
        arguments:
            phpexcel: @phpexcel

