services:
    choferes.servicios.usuario:
        class: ChoferesBundle\Servicios\UsuarioService
        arguments:
            entityManager: @doctrine.orm.entity_manager
    choferes.servicios.chofer:
        class: ChoferesBundle\Servicios\ChoferService
        arguments:
            entityManager: @doctrine.orm.entity_manager
            kernelCacheDir: "%kernel.cache_dir%"
            hashids: @hashids
            router: @router
            usuarioService: @choferes.servicios.usuario
        scope: request
    choferes.servicios.bajaAdministrativa:
        class: ChoferesBundle\Servicios\BajaAdministrativaService
        arguments:
            entityManager: @doctrine.orm.entity_manager
