curso:
    pattern:  /
    defaults: { _controller: "ChoferesBundle:Curso:index" }

curso_show:
    pattern:  /{id}/show
    defaults: { _controller: "ChoferesBundle:Curso:show" }

curso_new:
    pattern:  /new
    defaults: { _controller: "ChoferesBundle:Curso:new" }

curso_addchofer:
    pattern:  /addchofer
    defaults: { _controller: "ChoferesBundle:Curso:addchofer" }

curso_borrarchofer:
    pattern:  /borrarchofer
    defaults: { _controller: "ChoferesBundle:Curso:borrarChofer" }

curso_autocompletar:
    pattern:  /autocompletar
    defaults: { _controller: "ChoferesBundle:ChoferCurso:autocompletar" }

curso_create:
    pattern:  /create
    defaults: { _controller: "ChoferesBundle:Curso:create" }
    requirements: { _method: post }

curso_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ChoferesBundle:Curso:edit" }

curso_update:
    pattern:  /{id}/update
    defaults: { _controller: "ChoferesBundle:Curso:update" }
    requirements: { _method: post|put }

curso_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ChoferesBundle:Curso:delete" }
    requirements: { _method: post|delete }

curso_anteriores:
    pattern: /anteriores
    defaults: { _controller: "ChoferesBundle:Curso:indexCursosAnteriores" }

curso_precargados:
    pattern: /precargados
    defaults: { _controller: "ChoferesBundle:Curso:indexCursosPrecargados" }

curso_paraconfirmar:
    pattern: /paraconfirmar
    defaults: { _controller: "ChoferesBundle:Curso:indexCursosConfirmar" }

curso_confirmados:
    pattern: /confirmados
    defaults: { _controller: "ChoferesBundle:Curso:indexCursosConfirmados" }

curso_porvalidar:
    pattern: /porvalidar
    defaults: { _controller: "ChoferesBundle:Curso:indexCursosPorValidar" }

curso_validados:
    pattern: /validados
    defaults: { _controller: "ChoferesBundle:Curso:indexCursosValidados" }

curso_cancelados:
    pattern: /cancelados
    defaults: { _controller: "ChoferesBundle:Curso:indexCursosCancelados" }

curso_fallavalidacion:
    pattern: /fallavalidacion
    defaults: { _controller: "ChoferesBundle:Curso:indexCursosFallaValidacion" }

curso_confirmar:
    pattern: /{id}/confirmar
    defaults: { _controller: "ChoferesBundle:Curso:confirmarCurso" }

curso_cancelar:
    pattern: /{id}/cancelar
    defaults: { _controller: "ChoferesBundle:Curso:cancelarCurso" }

curso_realizar:
    pattern: /{id}/realizar
    defaults: { _controller: "ChoferesBundle:Curso:realizarCurso" }

curso_documentacion:
    pattern: /{id}/revisar
    defaults: { _controller: "ChoferesBundle:Curso:revisarDocumentacion" }

curso_carga_masiva_tri:
    pattern: /carga_masiva_tri
    defaults: { _controller: "ChoferesBundle:Curso:cargaMasivaTri" }

curso_create_comprobante_pago:
    pattern:  /{id}/create_comprobante_pago
    defaults: { _controller: "ChoferesBundle:ComprobantePago:create" }
    requirements: { _method: post }
