chofer_reporte_curso:
    pattern:  /choferxtipocurso
    defaults: { _controller: "ChoferesBundle:Chofer:reporteChoferesPorTipoCurso" }

chofer_reporte_prestador:
    pattern:  /choferxprestador
    defaults: { _controller: "ChoferesBundle:Chofer:reportePrestador" }

reporte_choferes_vigentes:
    pattern:  /choferes_vigentes
    defaults: { _controller: "ChoferesBundle:Reporte:choferesVigentes" }

reporte_cursos_por_tipo:
    pattern:  /cursosPorTipo
    defaults: { _controller: "ChoferesBundle:Reporte:cursosPorTipo" }

reporte_cursos_por_tipo_excel:
    pattern:  /cursosPorTipo/excel
    defaults: { _controller: "ChoferesBundle:Reporte:cursosPorTipoExcel" }
    requirements: { _method: post }