chofer_reporte_curso:
    pattern:  /choferxtipocurso
    defaults: { _controller: "ChoferesBundle:Chofer:reporteCurso" }

chofer_reporte_prestador:
    pattern:  /choferxprestador
    defaults: { _controller: "ChoferesBundle:Chofer:reportePrestador" }

reporte_choferes_vigentes:
    pattern:  /choferes_vigentes
    defaults: { _controller: "ChoferesBundle:Reporte:choferesVigentes" }
