chofer_reporte_curso:
    pattern:  /choferxtipocurso
    defaults: { _controller: "ChoferesBundle:Chofer:reporteChoferesPorTipoCurso" }

chofer_reporte_prestador:
    pattern:  /choferxprestador
    defaults: { _controller: "ChoferesBundle:Chofer:reportePrestador" }

reporte_choferes_vigentes:
    pattern:  /choferes_vigentes
    defaults: { _controller: "ChoferesBundle:Reporte:choferesVigentes" }

reporte_choferes_vigentes_cnrt:
    pattern:  /choferes_vigentes_cnrt
    defaults: { _controller: "ChoferesBundle:Reporte:choferesVigentesCNRT" }

reporte_choferes_vigentes_cntsv:
    pattern:  /choferes_vigentes_cntsv
    defaults: { _controller: "ChoferesBundle:Reporte:choferesVigentesCNTSV" }

reporte_cursos_por_tipo:
    pattern:  /cursosPorTipo
    defaults: { _controller: "ChoferesBundle:Reporte:cursosPorTipo" }
