chofer_reporte_curso:
    pattern:  /choferxtipocurso
    defaults: { _controller: "ChoferesBundle:Chofer:reporteChoferesPorTipoCurso" }

chofer_reporte_prestador:
    pattern:  /choferxprestador
    defaults: { _controller: "ChoferesBundle:Chofer:reportePrestador" }

reporte_choferes_vigentes_por_fecha_validacion:
    pattern:  /choferes_vigentes_por_fecha_validacion
    defaults: { _controller: "ChoferesBundle:Reporte:choferesVigentesPorFechaValidacion" }

reporte_total_choferes_vigentes_por_fecha_validacion:
    pattern:  /total_choferes_vigentes_por_fecha_validacion
    defaults: { _controller: "ChoferesBundle:Reporte:totalChoferesVigentesPorFechaValidacion" }

reporte_choferes_vigentes_por_fecha_curso:
    pattern:  /choferes_vigentes_por_fecha_curso
    defaults: { _controller: "ChoferesBundle:Reporte:choferesVigentesPorFechaCurso" }

reporte_total_choferes_vigentes_por_fecha_curso:
    pattern:  /total_choferes_vigentes_por_fecha_curso
    defaults: { _controller: "ChoferesBundle:Reporte:totalChoferesVigentesPorFechaCurso" }

reporte_cursos_por_tipo:
    pattern:  /cursosPorTipo
    defaults: { _controller: "ChoferesBundle:Reporte:cursosPorTipo" }

reporte_cursos_filtro:
    pattern:  /cursoFiltro
    defaults: { _controller: "ChoferesBundle:Reporte:cursoFiltro" }
