-- MySQL Script generated by MySQL Workbench
-- mié 01 jul 2015 10:30:04 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema choferes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `choferes` ;
-- -----------------------------------------------------
-- Schema choferes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `choferes` DEFAULT CHARACTER SET latin1 ;
USE `choferes` ;

-- -----------------------------------------------------
-- Table `choferes`.`chofer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`chofer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(8) NOT NULL,
  `precuil` VARCHAR(2) NULL DEFAULT NULL,
  `colacuil` VARCHAR(1) NULL DEFAULT NULL,
  `cuil_empresa` VARCHAR(11) NULL DEFAULT NULL,
  `tiene_curso_basico` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`prestador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cuit` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `logo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`docente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `prestador_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `prestador_docente_idx` (`prestador_id` ASC),
  CONSTRAINT `prestador_docente`
    FOREIGN KEY (`prestador_id`)
    REFERENCES `choferes`.`prestador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`estado_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`estado_curso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`sede` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `prestador_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `prestador_sede_idx` (`prestador_id` ASC),
  CONSTRAINT `prestador_sede`
    FOREIGN KEY (`prestador_id`)
    REFERENCES `choferes`.`prestador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`tipo_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`tipo_curso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`curso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `prestador_id` INT(11) NOT NULL,
  `tipoCurso_id` INT(11) NOT NULL,
  `docente_id` INT(11) NULL DEFAULT NULL,
  `sede_id` INT(11) NULL DEFAULT NULL,
  `estado_id` INT(11) NULL DEFAULT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `codigo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `prestador_curso_idx` (`prestador_id` ASC),
  INDEX `docente_curso_idx` (`docente_id` ASC),
  INDEX `tipoCurso_curso_idx` (`tipoCurso_id` ASC),
  INDEX `sede_curso_idx` (`sede_id` ASC),
  INDEX `estado_curso_idx` (`estado_id` ASC),
  CONSTRAINT `docente_curso`
    FOREIGN KEY (`docente_id`)
    REFERENCES `choferes`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estado_curso`
    FOREIGN KEY (`estado_id`)
    REFERENCES `choferes`.`estado_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prestador_curso`
    FOREIGN KEY (`prestador_id`)
    REFERENCES `choferes`.`prestador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sede_curso`
    FOREIGN KEY (`sede_id`)
    REFERENCES `choferes`.`sede` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoCurso_curso`
    FOREIGN KEY (`tipoCurso_id`)
    REFERENCES `choferes`.`tipo_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`chofer_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`chofer_curso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `chofer_id` INT(11) NOT NULL,
  `curso_id` INT(11) NOT NULL,
  `estado` BOOLEAN NOT NULL DEFAULT FALSE,
  `apagado` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  INDEX `chofer_curso_idx` (`chofer_id` ASC),
  INDEX `curso_chofer_idx` (`curso_id` ASC),
  CONSTRAINT `chofer_curso`
    FOREIGN KEY (`chofer_id`)
    REFERENCES `choferes`.`chofer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `curso_chofer`
    FOREIGN KEY (`curso_id`)
    REFERENCES `choferes`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  `activo` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`id`),
  INDEX `rol_usuario_idx` (`rol_id` ASC),
  CONSTRAINT `rol_usuario`
    FOREIGN KEY (`rol_id`)
    REFERENCES `choferes`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `choferes`.`usuario_prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `choferes`.`usuario_prestador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `prestador_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_prestador_idx` (`usuario_id` ASC),
  INDEX `prestador_usuario_idx` (`prestador_id` ASC),
  CONSTRAINT `prestador_usuario`
    FOREIGN KEY (`prestador_id`)
    REFERENCES `choferes`.`prestador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_prestador`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `choferes`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE sede CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE prestador_id prestador_id INT DEFAULT NULL;
ALTER TABLE usuario_prestador CHANGE prestador_id prestador_id INT DEFAULT NULL, CHANGE usuario_id usuario_id INT DEFAULT NULL;
ALTER TABLE chofer_curso CHANGE chofer_id chofer_id INT DEFAULT NULL, CHANGE curso_id curso_id INT DEFAULT NULL;
ALTER TABLE usuario CHANGE rol_id rol_id INT DEFAULT NULL, CHANGE activo activo TINYINT(1) DEFAULT '1';
ALTER TABLE curso CHANGE prestador_id prestador_id INT DEFAULT NULL, CHANGE tipoCurso_id tipoCurso_id INT DEFAULT NULL;

LOCK TABLES `choferes`.`rol` WRITE;
/*!40000 ALTER TABLE `choferes`.`rol` DISABLE KEYS */;
INSERT INTO `choferes`.`rol` VALUES (1,'ROLE_ADMIN');
/*!40000 ALTER TABLE `choferes`.`rol` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `choferes`.`usuario` WRITE;
/*!40000 ALTER TABLE `choferes`.`usuario` DISABLE KEYS */;
INSERT INTO `choferes`.`usuario` VALUES (1,'admin','admin@admin.com','$2a$12$7hFGMobKDxo5tthJcgxjDei1dxBdR5nJJ7HwghnTSn3p7yXE9sUxq',1,TRUE);
/*!40000 ALTER TABLE `choferes`.`usuario` ENABLE KEYS */;
UNLOCK TABLES;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
